Repository exercism/javascript-analyzer, pull requests merged in 2019-07, with the labels that each got.

#39 Tweak statuses
  CONTRIBUTING.md
  docs/comments.md
  docs/smoke-tests.md
  docs/snapshot-tests.md
  src/batch.ts
  src/interface.d.ts
  src/output/AnalyzerOutput.ts
  test/analyzers/resistor-color/__snapshots__/snapshot.ts.snap
  test/analyzers/resistor-color/smoke.ts
  test/analyzers/resistor-color/snapshot.ts
  test/analyzers/two-fer/__snapshots__/snapshot.ts.snap
  test/analyzers/two-fer/smoke.ts
  test/analyzers/two-fer/snapshot.ts
  test/output/AnalyzerOutput.ts
  test/output/toProcessable.ts
  test/smoke.ts
Labels: :wrench: chore

#40 Switch to templated output by default
  CHANGELOG.md
  package.json
  src/analyzers/gigasecond/index.ts
  src/analyzers/resistor-color/index.ts
  src/analyzers/two-fer/index.ts
  src/comments/shared.ts
  src/interface.d.ts
  src/output/AnalyzerOutput.ts
  src/utils/execution_options.ts
  test/analyzers/two-fer/__snapshots__/snapshot.ts.snap
  test/helpers/bootstrap.ts
  test/output/processor/FileOutput.ts
  test/output/processor/LogOutput.ts
  test/output/toProcessable.ts
Labels: :wrench: chore

#43 Update tag template format
  CHANGELOG.md
  package.json
  src/comments/comment.ts
  test/analyzers/two-fer/__snapshots__/snapshot.ts.snap
Labels: :wrench: chore

#38 gigasecond: Initial analyzer
  src/analyze.ts
  src/analyzers/IsolatedAnalyzerImpl.ts
  src/analyzers/SourceImpl.ts
  src/analyzers/gigasecond/GigasecondSolution.ts
  src/analyzers/gigasecond/index.ts
  src/analyzers/resistor-color/index.ts
  src/analyzers/utils/extract_main_body.ts
  src/analyzers/utils/extract_main_method.ts
  src/analyzers/utils/find_new_expression.ts
  src/analyzers/utils/find_top_level_constants.ts
  src/analyzers/utils/is_binary_expression.ts
  src/analyzers/utils/is_identifier.ts
  src/analyzers/utils/is_member_expression.ts
  src/analyzers/utils/is_variable_declaration_of_kind.ts
  src/comments/shared.ts
  src/errors/NoExportError.ts
  src/errors/NoMethodError.ts
  src/errors/StructureError.ts
  src/errors/codes.ts
  src/interface.d.ts
  src/output/AnalyzerOutput.ts
  src/output/IsolatedAnalyzerOutput.ts
  src/utils/execution_options.ts
  test/analyzers/gigasecond/__snapshots__/snapshot.ts.snap
  test/analyzers/gigasecond/smoke.ts
  test/analyzers/gigasecond/snapshot.ts
  test/helpers/bootstrap.ts
  test/output/processor/FileOutput.ts
  test/output/processor/LogOutput.ts
  test/output/toProcessable.ts
Labels: :sparkles: new exercise

#44 Two-fer: conditional flow in one-line function
  src/analyzers/AnalyzerImpl.ts
  src/analyzers/two-fer/index.ts
  test/analyzers/two-fer/__snapshots__/snapshot.ts.snap
  test/analyzers/two-fer/snapshot.ts
Labels: :bug: bug
