Repository exercism/javascript-analyzer, pull requests merged in 2019-05, with the labels that each got.

#3 Change preferredName extension to target javascript files
  src/solution.ts
Labels: :bug: bug

#4 Create LICENSE
  LICENSE
Labels: :book: documentation

#5 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: :book: documentation

#12 Add dockerfile for automated mentoring support
  .dockerignore
  Dockerfile
  README.md
  bin/analyze.sh
Labels: :wrench: chore
